import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
    title: "심심할때 만드는 거",
    description: "Generated by hoony",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ko">
            <body>{children}</body>
        </html>
    );
}
